// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Follow struct {
	FollowerID  int64              `json:"follower_id"`
	FollowingID int64              `json:"following_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Post struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	FullName     string             `json:"full_name"`
	Email        string             `json:"email"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
