// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFollow = `-- name: CreateFollow :one
INSERT INTO follows (follower_id, following_id)
VALUES ($1, $2)
RETURNING follower_id, following_id, created_at
`

type CreateFollowParams struct {
	FollowerID  int64 `json:"follower_id"`
	FollowingID int64 `json:"following_id"`
}

// --- FOLLOW ---
func (q *Queries) CreateFollow(ctx context.Context, arg CreateFollowParams) (Follow, error) {
	row := q.db.QueryRow(ctx, createFollow, arg.FollowerID, arg.FollowingID)
	var i Follow
	err := row.Scan(&i.FollowerID, &i.FollowingID, &i.CreatedAt)
	return i, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (user_id, content)
VALUES ($1, $2)
RETURNING id, user_id, content, created_at
`

type CreatePostParams struct {
	UserID  int64  `json:"user_id"`
	Content string `json:"content"`
}

// --- POST & FEED ---
func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost, arg.UserID, arg.Content)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, full_name, email)
VALUES ($1, $2, $3, $4)
RETURNING id, username, password_hash, full_name, email, created_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	FullName     string `json:"full_name"`
	Email        string `json:"email"`
}

// --- USER ---
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.FullName,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFollow = `-- name: DeleteFollow :exec
DELETE FROM follows 
WHERE follower_id = $1 AND following_id = $2
`

type DeleteFollowParams struct {
	FollowerID  int64 `json:"follower_id"`
	FollowingID int64 `json:"following_id"`
}

func (q *Queries) DeleteFollow(ctx context.Context, arg DeleteFollowParams) error {
	_, err := q.db.Exec(ctx, deleteFollow, arg.FollowerID, arg.FollowingID)
	return err
}

const getNewsFeed = `-- name: GetNewsFeed :many
SELECT 
    posts.id, 
    posts.content, 
    posts.created_at, 
    users.username AS author_name -- JOIN để lấy tên tác giả
FROM posts
JOIN users ON posts.user_id = users.id
WHERE posts.user_id IN (
    SELECT following_id 
    FROM follows 
    WHERE follower_id = $1 -- $1 là ID của chính mình
)
ORDER BY posts.created_at DESC
LIMIT $2 OFFSET $3
`

type GetNewsFeedParams struct {
	FollowerID int64 `json:"follower_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

type GetNewsFeedRow struct {
	ID         int64              `json:"id"`
	Content    string             `json:"content"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	AuthorName string             `json:"author_name"`
}

func (q *Queries) GetNewsFeed(ctx context.Context, arg GetNewsFeedParams) ([]GetNewsFeedRow, error) {
	rows, err := q.db.Query(ctx, getNewsFeed, arg.FollowerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNewsFeedRow
	for rows.Next() {
		var i GetNewsFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPost = `-- name: GetPost :one
SELECT id, user_id, content, created_at FROM posts WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPost(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, full_name, email, created_at FROM users WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const listPostsByUser = `-- name: ListPostsByUser :many
SELECT id, user_id, content, created_at FROM posts 
WHERE user_id = $1 
ORDER BY created_at DESC
`

func (q *Queries) ListPostsByUser(ctx context.Context, userID int64) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPostsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
