// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// --- FOLLOW ---
	CreateFollow(ctx context.Context, arg CreateFollowParams) (Follow, error)
	// --- POST & FEED ---
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	// --- USER ---
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteFollow(ctx context.Context, arg DeleteFollowParams) error
	GetNewsFeed(ctx context.Context, arg GetNewsFeedParams) ([]GetNewsFeedRow, error)
	GetPost(ctx context.Context, id int64) (Post, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListPostsByUser(ctx context.Context, userID int64) ([]Post, error)
}

var _ Querier = (*Queries)(nil)
