// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Sku       string             `json:"sku"`
	Price     int64              `json:"price"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
