// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getAllTicket = `-- name: GetAllTicket :many
SELECT id, quantity FROM tickets
`

func (q *Queries) GetAllTicket(ctx context.Context) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, getAllTicket)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(&i.ID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicketForUpdate = `-- name: GetTicketForUpdate :one
SELECT id, quantity FROM tickets 
WHERE id = $1 LIMIT 1 
FOR UPDATE
`

func (q *Queries) GetTicketForUpdate(ctx context.Context, id int32) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketForUpdate, id)
	var i Ticket
	err := row.Scan(&i.ID, &i.Quantity)
	return i, err
}

const updateTicket = `-- name: UpdateTicket :exec
UPDATE tickets 
SET quantity = $2 
WHERE id = $1
`

type UpdateTicketParams struct {
	ID       int32 `json:"id"`
	Quantity int32 `json:"quantity"`
}

func (q *Queries) UpdateTicket(ctx context.Context, arg UpdateTicketParams) error {
	_, err := q.db.Exec(ctx, updateTicket, arg.ID, arg.Quantity)
	return err
}
