// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	GetAllTicket(ctx context.Context) ([]Ticket, error)
	GetTicketForUpdate(ctx context.Context, id int32) (Ticket, error)
	UpdateTicket(ctx context.Context, arg UpdateTicketParams) error
}

var _ Querier = (*Queries)(nil)
